"""empty message

Revision ID: 0059f3cb1f15
Revises: aa91eb715845
Create Date: 2022-11-14 11:51:08.725129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0059f3cb1f15'
down_revision = 'aa91eb715845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculo', sa.Column('usado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculo', 'usado')
    # ### end Alembic commands ###
