"""empty message

Revision ID: 0b6d7cf280e6
Revises: 6f132fc0cdd5
Create Date: 2022-11-08 19:48:43.983921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6d7cf280e6'
down_revision = '6f132fc0cdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rotadia_data_id_fkey', 'rotadia', type_='foreignkey')
    op.create_foreign_key(None, 'rotadia', 'data', ['data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rotadia', type_='foreignkey')
    op.create_foreign_key('rotadia_data_id_fkey', 'rotadia', 'rotadia', ['data_id'], ['id'])
    # ### end Alembic commands ###
