"""empty message

Revision ID: 6f132fc0cdd5
Revises: 71762464d861
Create Date: 2022-11-08 19:44:08.734919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f132fc0cdd5'
down_revision = '71762464d861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rotadia_veiculo_id_fkey', 'rotadia', type_='foreignkey')
    op.drop_constraint('rotadia_motorista_id_fkey', 'rotadia', type_='foreignkey')
    op.drop_constraint('rotadia_rota_id_fkey', 'rotadia', type_='foreignkey')
    op.create_foreign_key(None, 'rotadia', 'motorista', ['motorista_id'], ['id'])
    op.create_foreign_key(None, 'rotadia', 'veiculo', ['veiculo_id'], ['id'])
    op.create_foreign_key(None, 'rotadia', 'rota', ['rota_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rotadia', type_='foreignkey')
    op.drop_constraint(None, 'rotadia', type_='foreignkey')
    op.drop_constraint(None, 'rotadia', type_='foreignkey')
    op.create_foreign_key('rotadia_rota_id_fkey', 'rotadia', 'rotadia', ['rota_id'], ['id'])
    op.create_foreign_key('rotadia_motorista_id_fkey', 'rotadia', 'rotadia', ['motorista_id'], ['id'])
    op.create_foreign_key('rotadia_veiculo_id_fkey', 'rotadia', 'rotadia', ['veiculo_id'], ['id'])
    # ### end Alembic commands ###
