"""empty message

Revision ID: 71762464d861
Revises: 
Create Date: 2022-11-08 19:37:20.176922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71762464d861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_rota', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rota_nome_rota'), 'rota', ['nome_rota'], unique=False)
    op.create_table('rotadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('finalizada', sa.Boolean(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('rota_id', sa.Integer(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['rotadia.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['rotadia.id'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['rotadia.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['rotadia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('telefone', sa.String(length=14), nullable=True),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('ultima_vez_lido_mensagem', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_is_admin'), 'usuario', ['is_admin'], unique=False)
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    op.create_index(op.f('ix_usuario_token'), 'usuario', ['token'], unique=True)
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('tamanho', sa.String(length=10), nullable=True),
    sa.Column('lugares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculo_lugares'), 'veiculo', ['lugares'], unique=False)
    op.create_index(op.f('ix_veiculo_modelo'), 'veiculo', ['modelo'], unique=False)
    op.create_index(op.f('ix_veiculo_placa'), 'veiculo', ['placa'], unique=False)
    op.create_index(op.f('ix_veiculo_tamanho'), 'veiculo', ['tamanho'], unique=False)
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=10), nullable=True),
    sa.Column('curso', sa.String(length=50), nullable=True),
    sa.Column('instituto', sa.String(length=10), nullable=True),
    sa.Column('periodo', sa.String(length=10), nullable=True),
    sa.Column('rotadia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rotadia_id'], ['rotadia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluno_categoria'), 'aluno', ['categoria'], unique=False)
    op.create_index(op.f('ix_aluno_curso'), 'aluno', ['curso'], unique=False)
    op.create_index(op.f('ix_aluno_instituto'), 'aluno', ['instituto'], unique=False)
    op.create_index(op.f('ix_aluno_periodo'), 'aluno', ['periodo'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['historico_id'], ['historico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('corpo', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_timestamp'), 'mensagem', ['timestamp'], unique=False)
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habilitacao', sa.String(length=10), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motorista_habilitacao'), 'motorista', ['habilitacao'], unique=False)
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacao_name'), 'notificacao', ['name'], unique=False)
    op.create_index(op.f('ix_notificacao_timestamp'), 'notificacao', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacao_timestamp'), table_name='notificacao')
    op.drop_index(op.f('ix_notificacao_name'), table_name='notificacao')
    op.drop_table('notificacao')
    op.drop_index(op.f('ix_motorista_habilitacao'), table_name='motorista')
    op.drop_table('motorista')
    op.drop_index(op.f('ix_mensagem_timestamp'), table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_table('data')
    op.drop_index(op.f('ix_aluno_periodo'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_instituto'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_curso'), table_name='aluno')
    op.drop_index(op.f('ix_aluno_categoria'), table_name='aluno')
    op.drop_table('aluno')
    op.drop_index(op.f('ix_veiculo_tamanho'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_placa'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_modelo'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_lugares'), table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index(op.f('ix_usuario_token'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_is_admin'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('rotadia')
    op.drop_index(op.f('ix_rota_nome_rota'), table_name='rota')
    op.drop_table('rota')
    op.drop_table('historico')
    # ### end Alembic commands ###
