"""empty message

Revision ID: a1851cece420
Revises: 0b6d7cf280e6
Create Date: 2022-11-08 20:11:27.564937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1851cece420'
down_revision = '0b6d7cf280e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('rota_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aluno', 'rota', ['rota_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aluno', type_='foreignkey')
    op.drop_column('aluno', 'rota_id')
    # ### end Alembic commands ###
