"""empty message

Revision ID: aa91eb715845
Revises: de52f3f449e6
Create Date: 2022-11-14 10:37:49.053538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa91eb715845'
down_revision = 'de52f3f449e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('respondido', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_aluno_respondido'), 'aluno', ['respondido'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aluno_respondido'), table_name='aluno')
    op.drop_column('aluno', 'respondido')
    # ### end Alembic commands ###
