"""empty message

Revision ID: de52f3f449e6
Revises: a1851cece420
Create Date: 2022-11-14 09:33:25.910090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de52f3f449e6'
down_revision = 'a1851cece420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('confirmado', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_aluno_confirmado'), 'aluno', ['confirmado'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aluno_confirmado'), table_name='aluno')
    op.drop_column('aluno', 'confirmado')
    # ### end Alembic commands ###
